line-length: false
no-hard-tabs:
  code_blocks: false
  spaces_per_tab: 2
no-inline-html:
  allowed_elements: [small, strong, u, iframe]
no-blanks-blockquote: false
ul-style:
  style: dash
ol-prefix:
  style: ordered
hr-style:
  style: ---
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: underscore
strong-style:
  style: asterisk
