[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://fynn.netlify.app/*"
  to = "https://fynn.be/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://mvsde.com/*"
  to = "https://fynn.be/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://talks.fynn.be/*"
  to = "https://fynn.be/talks/"
  status = 302
  force = true

[[redirects]]
  from = "/blog/return-of-fabulousness/"
  to = "/blog/down-the-rabbit-hole/"
  status = 301

[[redirects]]
  from = "/blog/exploring-fabulousness/"
  to = "/blog/down-the-rabbit-hole/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = [
      "dist/img"
    ]
