[build]
  environment = { NODE_VERSION = "13" }

[context.production]
  publish = "dist/pages"
  command = "npm run build:pages"

[context.twitter]
  publish = "dist/twitter"
  command = "npm run build:twitter"

[[redirects]]
  from = "https://fynn.netlify.com/*"
  to = "https://fynn.be/:splat"
