[build]
  publish = "dist"
  command = "npm run build"

[context.production]
  environment = { NODE_VERSION = "13" }

[[redirects]]
  from = "https://fynn.netlify.com/*"
  to = "https://fynn.be/:splat"
