[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "15"

[[redirects]]
  from = "https://fynn.netlify.app/*"
  to = "https://fynn.be/:splat"
  force = true

[[redirects]]
  from = "https://mvsde.com/*"
  to = "https://fynn.be/:splat"
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    permissions-policy = "interest-cohort=()"
