[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "https://fynn.netlify.app/*"
  to = "https://fynn.be/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://mvsde.com/*"
  to = "https://fynn.be/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://talks.fynn.be/*"
  to = "https://fynn.be/talks/"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    permissions-policy = "interest-cohort=()"
