[build.environment]
  NODE_VERSION = "13"
  GIT_LFS_SKIP_SMUDGE = "1"

[context.production]
  publish = "dist/site"
  command = "npm run build:site"

[context.twitter]
  publish = "dist/twitter"
  command = "git clone git@github.com:mvsde/twitter-data.git ../twitter-data && npm run build:twitter"

[[redirects]]
  from = "https://fynn.netlify.com/*"
  to = "https://fynn.be/:splat"
