[build.environment]
  NODE_VERSION = "14"
  GIT_LFS_SKIP_SMUDGE = "1"

[context.production]
  publish = "dist/site"
  command = "npm run build:site && npm run build:css:site"

[context.twitter]
  publish = "dist/twitter"
  command = "git clone https://github.com/mvsde/twitter-data.git ../twitter-data && npm run build:twitter && npm run build:css:twitter"

[[redirects]]
  from = "https://fynn.netlify.app/*"
  to = "https://fynn.be/:splat"
